"""Tests for report generation module."""

import pandas as pd

from sequence_analyzer.core.report import (
    generate_html_report,
    generate_methods_section,
    generate_pdf_report,
)


class TestGenerateMethodsSection:
    def test_contains_sequence_count(self):
        text = generate_methods_section(seq_count=12, qc_pass_count=10)
        assert "12" in text
        assert "10" in text

    def test_contains_alignment_method_msa(self):
        text = generate_methods_section(seq_count=5, qc_pass_count=5, alignment_method="msa")
        assert "multiple sequence alignment" in text

    def test_contains_alignment_method_pairwise(self):
        text = generate_methods_section(seq_count=5, qc_pass_count=5, alignment_method="pairwise")
        assert "pairwise alignment" in text

    def test_contains_tree_method_nj(self):
        text = generate_methods_section(seq_count=5, qc_pass_count=5, tree_method="nj")
        assert "Neighbor-Joining" in text

    def test_contains_tree_method_upgma(self):
        text = generate_methods_section(seq_count=5, qc_pass_count=5, tree_method="upgma")
        assert "UPGMA" in text

    def test_contains_bootstrap_replicates(self):
        text = generate_methods_section(seq_count=5, qc_pass_count=5, bootstrap_replicates=100)
        assert "100" in text

    def test_contains_gc_window_size(self):
        text = generate_methods_section(seq_count=5, qc_pass_count=5, gc_window_size=50)
        assert "50" in text

    def test_uses_past_tense(self):
        text = generate_methods_section(seq_count=5, qc_pass_count=5)
        # Check for past tense verbs
        assert "were submitted" in text
        assert "were aligned" in text
        assert "was constructed" in text
        assert "was calculated" in text

    def test_contains_version(self):
        from sequence_analyzer import __version__

        text = generate_methods_section(seq_count=5, qc_pass_count=5)
        assert __version__ in text

    def test_contains_seq_type(self):
        text = generate_methods_section(seq_count=5, qc_pass_count=5, seq_type="RNA")
        assert "RNA" in text


class TestGenerateHtmlReport:
    def test_contains_title(self):
        html = generate_html_report(title="My Analysis", methods_section="Methods here.")
        assert "My Analysis" in html

    def test_contains_methods(self):
        html = generate_html_report(title="Test", methods_section="Sequences were analyzed.")
        assert "Sequences were analyzed." in html

    def test_contains_qc_table_when_provided(self):
        df = pd.DataFrame({"ID": ["seq1"], "Status": ["Pass"]})
        html = generate_html_report(title="Test", methods_section="M", qc_table=df)
        assert "seq1" in html
        assert "Quality Control" in html

    def test_omits_qc_section_when_none(self):
        html = generate_html_report(title="Test", methods_section="M", qc_table=None)
        assert "Quality Control" not in html

    def test_contains_analysis_table_when_provided(self):
        df = pd.DataFrame({"Sequence": ["s1"], "GC_Content": [52.0]})
        html = generate_html_report(title="Test", methods_section="M", analysis_table=df)
        assert "Sequence Analysis" in html
        assert "52.0" in html

    def test_contains_alignment_summary(self):
        html = generate_html_report(
            title="Test", methods_section="M", alignment_summary="Identity: 95.2%"
        )
        assert "Alignment" in html
        assert "Identity: 95.2%" in html

    def test_contains_tree_newick(self):
        html = generate_html_report(title="Test", methods_section="M", tree_newick="(A:0.1,B:0.2);")
        assert "Phylogenetic Tree" in html
        assert "(A:0.1,B:0.2);" in html

    def test_contains_notes(self):
        html = generate_html_report(
            title="Test", methods_section="M", notes="Sample was from Lagos."
        )
        assert "Notes" in html
        assert "Sample was from Lagos." in html

    def test_contains_version_and_date(self):
        from sequence_analyzer import __version__

        html = generate_html_report(title="Test", methods_section="M")
        assert __version__ in html
        assert "Generated by Sequence Analyzer" in html

    def test_escapes_html_in_title(self):
        html = generate_html_report(title="<script>alert('xss')</script>", methods_section="M")
        assert "<script>" not in html
        assert "&lt;script&gt;" in html

    def test_is_valid_html_structure(self):
        html = generate_html_report(title="Test", methods_section="Methods.")
        assert html.startswith("<!DOCTYPE html>")
        assert "</html>" in html
        assert "<body>" in html


class TestGeneratePdfReport:
    def test_produces_bytes(self):
        html = generate_html_report(title="Test Report", methods_section="Methods text here.")
        pdf = generate_pdf_report(html)
        assert isinstance(pdf, bytes)
        assert len(pdf) > 100

    def test_pdf_starts_with_magic_bytes(self):
        html = generate_html_report(title="PDF Test", methods_section="M")
        pdf = generate_pdf_report(html)
        # PDF files start with %PDF
        assert pdf[:4] == b"%PDF"

    def test_handles_empty_content(self):
        html = "<html><body></body></html>"
        pdf = generate_pdf_report(html)
        assert isinstance(pdf, bytes)
        assert pdf[:4] == b"%PDF"
