[theme]
primaryColor = "#4CAF50"  # Genomic Green
backgroundColor = "#F8F9FA"  # Lighter Gray for a clean look
secondaryBackgroundColor = "#34495E"  # Darker Blue-Grey for better contrast
textColor = "black"  # Light Gray for better readability on dark areas
font = "sans serif"

[server]
port = 8501