[theme]
primaryColor = "#4CAF50"  # Genomic Green - highlights key elements
backgroundColor = "#F5F5F5"  # Soft Light Gray - reduces eye strain
secondaryBackgroundColor = "#1B3A4B"  # Deep Blue-Green - suitable for bioinformatics
textColor = "#1C1C1C"  # Dark Gray - improves readability
font = "sans serif"

[server]
port = 8501