[theme]
# Genomic green for vibrance & branding
primaryColor = "#2E7D32"

# Light background for clarity
backgroundColor ="#1E1E1E"

# Secondary background for sidebar & menus
secondaryBackgroundColor = "#2C3E50"

# High-contrast text for readability
textColor = "#EAEAEA"

# Consistent modern font
font = "sans serif"

# Optional: Set spacing & rounding via global CSS if needed
# You can also inject custom fonts or styles via markdown in main app

[server]
# Run Streamlit on port 8501
port = 8501

# Cross-Origin access (True if deploying externally)
enableCORS = true

# Upload size limit (MB)
maxUploadSize = 200

# Deployment-ready: no browser popup
headless = true

# Optional: Improve dev performance
enableXsrfProtection = false
