[theme]
primaryColor = "#4CAF50"  # Genomic Green
backgroundColor = "#F5F5F5"  # Soft Light Gray
secondaryBackgroundColor = "#2B3A67"  # Adjusted to a softer dark blue
textColor = "#FFFFFF"  # White text for visibility on dark areas
font = "sans serif"

[server]
port = 8501